import { readFileSync } from "node:fs";
import { join } from "node:path";
import { describe, expect, it } from "vitest";
import { FIXED_ROUTES, type VehicleCode } from "@/lib/fixed-prices";
import { VEHICLE_CATALOG, EXTRAS_CATALOG } from "@/types";
import { SUPPORTED_LOCALES } from "@/lib/i18n";

/**
 * public/llms.txt and llms-full.txt are served to GPTBot, ClaudeBot,
 * PerplexityBot, OAI-SearchBot and Google-Extended, all of which robots.txt
 * explicitly allows. They were hand-maintained and drifted badly: an audit on
 * 24 Aug 2026 found 136 of 175 price cells wrong, nearly all quoting less than
 * the site charges, plus invented ratings from Trustpilot and TripAdvisor
 * profiles that do not exist.
 *
 * They are now generated by scripts/generate-llms.mts. These tests fail if the
 * committed files drift from the data again, or if fabricated social proof
 * comes back.
 */
const brief = readFileSync(join(process.cwd(), "public", "llms.txt"), "utf-8");
const full = readFileSync(join(process.cwd(), "public", "llms-full.txt"), "utf-8");
const FILES: Array<[string, string]> = [["llms.txt", brief], ["llms-full.txt", full]];

const COLS: VehicleCode[] = ["ECONOMY", "BUSINESS", "MINIVAN", "VCLASS", "MINIBUS"];

function tableRows(text: string): Map<string, number[]> {
  const out = new Map<string, number[]>();
  for (const line of text.split("\n")) {
    if (!line.startsWith("|")) continue;
    const cells = line.slice(1).split("|").map((c) => c.trim());
    if (cells.length < 6) continue;
    if (cells[0] === "Destination" || /^[-—\s]*$/.test(cells[0])) continue;
    const nums = cells.slice(1, 6).map((c) => {
      const m = /(\d+)/.exec(c);
      return m ? Number(m[1]) : NaN;
    });
    if (nums.every((n) => Number.isNaN(n))) continue;
    if (!out.has(cells[0])) out.set(cells[0], nums);
  }
  return out;
}

describe("no fabricated social proof reaches AI crawlers", () => {
  const BANNED = [
    /trustpilot/i,
    /tripadvisor/i,
    /\b312\b/,
    /\b189\b/,
    /\b94\+/,
    /4\.9\s*★/,
    /4\.8\s*★/,
    /\d+\+?\s*reviews/i,
  ];

  it.each(FILES)("%s carries no rating or review-count claim", (_name, text) => {
    for (const pattern of BANNED) {
      expect(pattern.test(text), `matched ${pattern}`).toBe(false);
    }
  });
});

describe("stated facts match the site's own data", () => {
  it.each(FILES)("%s lists the real fleet size", (_name, text) => {
    expect(text).toContain(`${VEHICLE_CATALOG.length} vehicles`);
  });

  it.each(FILES)("%s states each vehicle's real passenger limit", (_name, text) => {
    for (const v of VEHICLE_CATALOG) {
      // The old files claimed 4 passengers for the Corolla and Camry, which
      // carry 3, and 7 for the Vito, which carries 8.
      const line = text.split("\n").find((l) => l.includes(v.label));
      expect(line, `${v.label} missing`).toBeTruthy();
      // The two files word this differently — "up to N passengers" in the
      // brief, "Passengers: up to N" in the full one. Assert the number, not
      // the phrasing.
      expect(text).toMatch(new RegExp(`up to ${v.maxPassengers}\\b`));
    }
  });

  it.each(FILES)("%s counts routes from the route table", (_name, text) => {
    expect(text).toContain(`${FIXED_ROUTES.length} fixed`);
  });

  it.each(FILES)("%s lists every published language", (_name, text) => {
    // The old files claimed Catalan, which the site does not publish.
    expect(text).not.toMatch(/Catalan/);
    expect(text).toMatch(/English, Spanish, French/);
    expect(SUPPORTED_LOCALES.length).toBe(8);
  });

  it.each(FILES)("%s prices child seats and meet & greet as paid extras", (_name, text) => {
    // Both were listed as included in the fare. They are €5 options.
    expect(text).not.toMatch(/child seats?[^.\n]*free/i);
    const seat = EXTRAS_CATALOG.find((e) => e.id === "baby_seat");
    const greet = EXTRAS_CATALOG.find((e) => e.id === "meet_greet");
    expect(text).toContain(`Baby Seat — ${seat!.priceLabel}`);
    expect(text).toContain(`Meet & Greet — ${greet!.priceLabel}`);
  });

  it.each(FILES)("%s states the real free-waiting allowances", (_name, text) => {
    // The old files said 30 minutes away from airports; the site says 15.
    // Wording differs between the two files, so match on the allowances.
    expect(text).toMatch(/60 minutes free/i);
    expect(text).toMatch(/15 minutes free/i);
    expect(text).not.toMatch(/30 minutes free waiting/i);
  });

  it.each(FILES)("%s makes no unverifiable vehicle-age or refreshment claim", (_name, text) => {
    expect(text).not.toMatch(/under 3 years old/i);
    expect(text).not.toMatch(/complimentary still water/i);
  });
});

describe("every published price matches the route table", () => {
  it.each(FILES)("%s quotes no price the booking system would not charge", (name, text) => {
    const rows = tableRows(text);
    expect(rows.size, `${name} has no price rows`).toBeGreaterThan(30);

    const byLabel = new Map<string, (typeof FIXED_ROUTES)[number]>();
    for (const r of FIXED_ROUTES) {
      const label = r.from === r.to ? (r.note ?? r.toLabel) : r.toLabel;
      if (!byLabel.has(label)) byLabel.set(label, r);
    }

    let checked = 0;
    for (const [label, nums] of rows) {
      const route = byLabel.get(label);
      if (!route) continue;
      COLS.forEach((col, i) => {
        if (Number.isNaN(nums[i])) return;
        checked++;
        expect(nums[i], `${name}: ${label} ${col}`).toBe(route.prices[col]);
      });
    }
    expect(checked, `${name} compared too few cells`).toBeGreaterThan(100);
  });
});
